version: "3"

volumes:
  mysql-data:

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "conduit"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
